# Generated by Django 5.2.16 on 2026-07-11 19:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSimuladoTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_titulo', models.CharField(db_index=True, max_length=80, unique=True)),
                ('titular_ruc', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Ingrese una cédula o RUC de 10 a 13 dígitos.', regex='^\\d{10,13}$')])),
                ('tipo_nota', models.CharField(choices=[('DESMATERIALIZADA_ORDINARIA', 'Nota de crédito desmaterializada ordinaria'), ('ISD', 'Nota de crédito ISD'), ('C4T', 'Nota de crédito proveniente de C4T'), ('REINTEGRO_TRIBUTARIO', 'Nota de crédito de reintegro tributario'), ('CARTULAR_PENDIENTE_CANJE', 'Nota cartular pendiente de canje')], max_length=40)),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('estado', models.CharField(default='VIGENTE', max_length=100)),
                ('bloqueada', models.BooleanField(default=False)),
                ('motivo_bloqueo', models.CharField(blank=True, max_length=300)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'registro simulado de título',
                'verbose_name_plural': 'registros simulados de títulos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_relacion', models.CharField(choices=[('COMPRADOR', 'Comprador'), ('VENDEDOR', 'Vendedor'), ('AMBOS', 'Comprador y vendedor')], db_index=True, max_length=12)),
                ('ruc_identificacion', models.CharField(db_index=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese una cédula o RUC de 10 a 13 dígitos.', regex='^\\d{10,13}$')], verbose_name='RUC o identificación')),
                ('nombre_razon_social', models.CharField(db_index=True, max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('representante_legal', models.CharField(blank=True, max_length=200)),
                ('identificacion_representante', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Ingrese una cédula o RUC de 10 a 13 dígitos.', regex='^\\d{10,13}$')])),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('estado_cuenta_sri', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('PENDIENTE', 'Pendiente de consulta'), ('NO_DETERMINADO', 'No determinado')], default='PENDIENTE', max_length=20)),
                ('autorizacion_consulta', models.BooleanField(default=False, help_text='El cliente autorizó consultar y reutilizar información para el caso.')),
                ('autorizacion_fecha', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre_razon_social'],
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_titulo', models.CharField(db_index=True, max_length=80, unique=True)),
                ('tipo_nota', models.CharField(choices=[('DESMATERIALIZADA_ORDINARIA', 'Nota de crédito desmaterializada ordinaria'), ('ISD', 'Nota de crédito ISD'), ('C4T', 'Nota de crédito proveniente de C4T'), ('REINTEGRO_TRIBUTARIO', 'Nota de crédito de reintegro tributario'), ('CARTULAR_PENDIENTE_CANJE', 'Nota cartular pendiente de canje')], max_length=40)),
                ('origen_tributario', models.CharField(choices=[('PAGO_INDEBIDO', 'Pago indebido'), ('PAGO_EXCESO', 'Pago en exceso'), ('DEVOLUCION_IVA', 'Devolución de IVA'), ('DEVOLUCION_RENTA', 'Devolución de Impuesto a la Renta'), ('DEVOLUCION_ISD', 'Devolución de ISD'), ('CERTIFICADO_ABONO_TRIBUTARIO', 'Certificado de Abono Tributario'), ('OTRO', 'Otro / por determinar')], max_length=40)),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('saldo_disponible', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimo_recibir', models.DecimalField(decimal_places=2, help_text='Monto mínimo que el vendedor está dispuesto a recibir.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('estado_fuente', models.CharField(blank=True, max_length=100)),
                ('bloqueada', models.BooleanField(default=False)),
                ('motivo_bloqueo', models.CharField(blank=True, max_length=300)),
                ('estado_flujo', models.CharField(choices=[('BORRADOR', 'Borrador de recepción'), ('PENDIENTE_VALIDACION', 'Pendiente de validación'), ('CORRECCION_REQUERIDA', 'Corrección requerida'), ('VALIDADA', 'Validada por contador'), ('RECHAZADA', 'Rechazada'), ('EN_NEGOCIACION', 'En preparación de negociación'), ('PENDIENTE_CONFIRMACIONES', 'Pendiente de confirmaciones'), ('LISTA_LIQUIDACION', 'Lista para solicitud de liquidación'), ('CERRADA_DEMO', 'Cierre registrado en demostración')], db_index=True, default='BORRADOR', max_length=35)),
                ('observaciones_recepcion', models.TextField(blank=True)),
                ('observaciones_validacion', models.TextField(blank=True)),
                ('observaciones_negociacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('enviado_validacion_en', models.DateTimeField(blank=True, null=True)),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
                ('iniciado_negociacion_en', models.DateTimeField(blank=True, null=True)),
                ('cliente_comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_compradas', to='credit_notes.cliente')),
                ('cliente_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_vendidas', to='credit_notes.cliente')),
                ('contador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_validadas', to=settings.AUTH_USER_MODEL)),
                ('recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_recepcionadas', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_negociadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EventoTrazabilidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(db_index=True, max_length=80)),
                ('descripcion', models.TextField()),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_trazabilidad', to=settings.AUTH_USER_MODEL)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='credit_notes.notacredito')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoRespaldo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('NOTA_CREDITO', 'Nota de crédito'), ('AUTORIZACION', 'Autorización del cliente'), ('PODER_ENDOSO', 'Poder / autorización de endoso'), ('ESTADO_CUENTA', 'Estado de cuenta SRI'), ('IDENTIFICACION', 'Identificación'), ('OTRO', 'Otro')], max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('archivo_url', models.URLField(blank=True, help_text='URL en Vercel Blob, S3, Supabase Storage u otro almacenamiento externo.')),
                ('texto_extraido', models.TextField(blank=True, help_text='Texto pegado o extraído para demostrar búsqueda y asistencia IA.')),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('fuente', models.CharField(default='Cargado por operador', max_length=120)),
                ('cargado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cargado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cargados', to=settings.AUTH_USER_MODEL)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='credit_notes.notacredito')),
            ],
            options={
                'ordering': ['-cargado_en'],
            },
        ),
        migrations.CreateModel(
            name='OrdenNegociacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('porcentaje_descuento', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('fecha_propuesta', models.DateField(default=django.utils.timezone.localdate)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('terminos', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA_OPERADOR', 'Aprobada por operador'), ('ENVIADA_CONFIRMACION', 'Enviada a confirmación'), ('CONFIRMADA_PARTES', 'Confirmada por ambas partes')], db_index=True, default='BORRADOR', max_length=24)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_comprador', to='credit_notes.cliente')),
                ('nota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_negociacion', to='credit_notes.notacredito')),
                ('preparado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_preparadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('NEGOCIACION', 'Ficha de negociación'), ('ESTADO', 'Reporte de estado'), ('CIERRE', 'Reporte de cierre')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('contenido', models.JSONField(default=dict)),
                ('modelo_ia', models.CharField(blank=True, max_length=80)),
                ('generado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_ia', to='credit_notes.notacredito')),
            ],
            options={
                'ordering': ['-generado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAprobacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('parte', models.CharField(choices=[('VENDEDOR', 'Vendedor inicial'), ('COMPRADOR', 'Comprador')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], db_index=True, default='PENDIENTE', max_length=10)),
                ('confirmado_por', models.CharField(blank=True, max_length=200)),
                ('correo_confirmacion', models.EmailField(blank=True, max_length=254)),
                ('comentario', models.TextField(blank=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_aprobacion', to='credit_notes.cliente')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='credit_notes.ordennegociacion')),
            ],
        ),
        migrations.CreateModel(
            name='SugerenciaIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campo', models.CharField(max_length=80)),
                ('valor_actual', models.TextField(blank=True)),
                ('valor_sugerido', models.TextField()),
                ('confianza', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fuente', models.CharField(max_length=160)),
                ('evidencia', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], db_index=True, default='PENDIENTE', max_length=12)),
                ('generada_por_modelo', models.CharField(blank=True, max_length=80)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('revisada_en', models.DateTimeField(blank=True, null=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_ia', to='credit_notes.notacredito')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sugerencias_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['estado', 'campo'],
            },
        ),
        migrations.CreateModel(
            name='ValidacionNota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fuente', models.CharField(choices=[('SIMULADA', 'Fuente simulada'), ('CARGADA', 'Archivo cargado por el equipo'), ('REAL', 'Integración real')], max_length=12)),
                ('existe', models.BooleanField(default=False)),
                ('saldo_fuente', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estado_fuente', models.CharField(blank=True, max_length=100)),
                ('bloqueada', models.BooleanField(default=False)),
                ('motivo_bloqueo', models.CharField(blank=True, max_length=300)),
                ('campos_faltantes', models.JSONField(blank=True, default=list)),
                ('inconsistencias', models.JSONField(blank=True, default=list)),
                ('duplicados', models.JSONField(blank=True, default=list)),
                ('coincidencias_riesgo', models.JSONField(blank=True, default=list)),
                ('siguiente_accion', models.CharField(blank=True, max_length=300)),
                ('explicacion_ia', models.TextField(blank=True)),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFORME', 'Conforme'), ('OBSERVADA', 'Observada'), ('NO_CONFORME', 'No conforme')], db_index=True, default='PENDIENTE', max_length=15)),
                ('realizada_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='credit_notes.notacredito')),
                ('realizada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-realizada_en'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ruc_identificacion', 'tipo_relacion'], name='credit_note_ruc_ide_7f4739_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['creado_en'], name='credit_note_creado__174ded_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['estado_flujo', 'creado_en'], name='credit_note_estado__77749d_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['cliente_vendedor', 'estado_flujo'], name='credit_note_cliente_7c40e1_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['tipo_nota', 'origen_tributario'], name='credit_note_tipo_no_4b9078_idx'),
        ),
        migrations.AddIndex(
            model_name='eventotrazabilidad',
            index=models.Index(fields=['nota', 'creado_en'], name='credit_note_nota_id_d1b1ab_idx'),
        ),
        migrations.AddIndex(
            model_name='documentorespaldo',
            index=models.Index(fields=['nota', 'tipo_documento'], name='credit_note_nota_id_90774f_idx'),
        ),
        migrations.AddIndex(
            model_name='ordennegociacion',
            index=models.Index(fields=['estado', 'creado_en'], name='credit_note_estado_f31e71_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitudaprobacion',
            constraint=models.UniqueConstraint(fields=('orden', 'parte'), name='unique_approval_party_per_order'),
        ),
        migrations.AddConstraint(
            model_name='sugerenciaia',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('nota', 'campo'), name='unique_pending_suggestion_per_field'),
        ),
        migrations.AddIndex(
            model_name='validacionnota',
            index=models.Index(fields=['nota', 'resultado', 'realizada_en'], name='credit_note_nota_id_cf4d1e_idx'),
        ),
    ]
